### ISSUE TITLE
Error when building: Could not find a package configuration file provided by "gpuac_base"

### ISSUE THREAD

**Issue by mvanlobensels** [ZhenshengLee/perception_cupoch#1]
When building, I get the following error on the foxy branch on an Nvidia Jetson Nano:
![image](https://user-images.githubusercontent.com/50023316/129051398-6e66eaa1-2752-43c0-9190-c4e4f9f1c04c.png)

The CMakeLists references a `gpuac_base`, but I am unable to find online what that is. Any help would be appreciated!

**Comment by ZhenshengLee** [comment]
> When building, I get the following error on the foxy branch on an Nvidia Jetson Nano:
> ![image](https://user-images.githubusercontent.com/50023316/129051398-6e66eaa1-2752-43c0-9190-c4e4f9f1c04c.png)
> 
> The CMakeLists references a `gpuac_base`, but I am unable to find online what that is. Any help would be appreciated!

Thanks for your report. I'll fix this in days.

**Comment by ZhenshengLee** [comment]
@mvanlobensels the foxy branch may work now, tell me if you encounter any problems.

**Comment by ZhenshengLee** [comment]
@mvanlobensels 

The Email has been received.

And there are issues to send msg to Gmail.

I suggest the way is to use gitter, you can use gitter via github account.

Thanks for your report.

I will write a wiki in github repo about using cupoch with ros and cpp, both in the Linux bare mental and docker context.

VictorLee

**Comment by ZhenshengLee** [comment]
Build errors will be tracked with this issue https://github.com/ZhenshengLee/perception_cupoch/issues/14

Closing this.
