### ISSUE TITLE
Using cupoch_conversions from other package

### ISSUE THREAD

**Issue by OrcunCanDeniz** [ZhenshengLee/perception_cupoch#16]
I was able to compile this package and test nodes are also running as expected. However couldnt manage to use cupoch_conversions from another package. 

``` In file included from /home/orcun/test_ws/src/prep_cupoch/src/prep_cupoch_node.cpp:5:0:
/home/orcun/test_ws/src/perception_cupoch/cupoch_conversions/include/cupoch_conversions/cupoch_conversions.h:19:10: fatal error: cupoch/cupoch.h: No such file or directory
 #include "cupoch/cupoch.h"
```

```prep_cupoch/
├── CMakeLists.txt
├── include
│   └── prep_cupoch
├── package.xml
└── src
    └── prep_cupoch_node.cpp

```

My cmake;
``` cmake_minimum_required(VERSION 3.0.2)
project(prep_cupoch)

## Compile as C++11, supported in ROS Kinetic and newer
# add_compile_options(-std=c++11)

## Find catkin macros and libraries
## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
## is used, also find other catkin packages
find_package(catkin REQUIRED COMPONENTS
  cupoch_conversions
  roscpp
  sensor_msgs
  tf2
  tf2_ros
)


catkin_package(
 INCLUDE_DIRS include
 LIBRARIES prep_cupoch
 CATKIN_DEPENDS cupoch_conversions roscpp sensor_msgs tf2 tf2_ros
 DEPENDS system_lib
)

include_directories(
include
  ${catkin_INCLUDE_DIRS}
)

${catkin_EXPORTED_TARGETS})

add_executable(${PROJECT_NAME}_node src/prep_cupoch_node.cpp)

add_dependencies(${PROJECT_NAME}_node ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
```

And a  ```#include "cupoch_conversions/cupoch_conversions.h"``` in the beginning of src/prep_cupoch_node.cpp.

**Comment by ZhenshengLee** [comment]
@OrcunCanDeniz 
Did you add dependencies in `package.xml`?

It's about usage of ROS of using header files from other ros packages.

You can refer this article for more info and have a try with https://roboticsbackend.com/ros-include-cpp-header-from-another-package/

Thanks.

**Comment by OrcunCanDeniz** [comment]
Well i pretty much adopted the project structure and cmake contents from [here](https://github.com/ZhenshengLee/ga_points_downsampler) and it worked.

**Comment by ZhenshengLee** [comment]
@OrcunCanDeniz 
Feel free to create issues in this repo and https://github.com/ZhenshengLee/ga_points_downsampler

Thanks.
